spring.application.name=user-service

server.servlet.context-path=/users
server.port=8200

jwt.secretKey = ancdabvdgjgj2migpgnpernvperwng3wuognvpawfvwpausuii

spring.datasource.url=jdbc:postgresql://localhost:5432/rahmaUsersDB
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.instance.hostname= localhost
eureka.instance.prefer-ip-address=false
